"""Create reference tables with pandas.

The final paper tables are generated by 09_make_tables.R with tinytable.
This Python implementation is retained as a reference/alternative table
workflow and is intentionally not called by run_all.py.
"""

from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]
TABLES_PATH = PROJECT_ROOT / "outputs/tables"
REFERENCE_PATH = PROJECT_ROOT / "outputs/tables/python_reference"


def save_latex(source_name: str, output_name: str, index: bool = False) -> None:
    source = TABLES_PATH / source_name
    if not source.exists():
        return

    df = pd.read_csv(source)
    latex = df.to_latex(index=index, escape=True)
    (REFERENCE_PATH / output_name).write_text(latex, encoding="utf-8")


def main() -> None:
    REFERENCE_PATH.mkdir(parents=True, exist_ok=True)

    save_latex("data_profile.csv", "data_profile_reference.tex")
    save_latex("data_quality_summary.csv", "data_quality_reference.tex")
    save_latex("hourly_summary.csv", "hourly_results_reference.tex")
    save_latex("weekday_summary.csv", "weekday_reference.tex")
    save_latex("hourly_2024_vs_since_2025.csv", "historical_reference.tex")

    print(f"Saved Python reference tables to {REFERENCE_PATH}.")


if __name__ == "__main__":
    main()
